apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-management-service
  template:
    metadata:
      labels:
        app: course-management-service
    spec:
      containers:
      - name: course-management-service
        image: bihesha1999/course-management-service:latest
        ports:
        - containerPort: 3002
          resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"