apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-management-service
  template:
    metadata:
      labels:
        app: payment-management-service
    spec:
      containers:
      - name: payment-management-service
        image: bihesha1999/payment-management-service_image:latest
        ports:
        - containerPort: 3003
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"