apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
      - name: user-management-service
        image: bihesha1999/user-management-service_image:latest
        ports:
          - containerPort: 3001
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: user-management-secrets
                key: USER_MANAGEMENT_MONGODB_URL
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: user-management-secrets
                key: USER_MANAGEMENT_CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: user-management-secrets
                key: USER_MANAGEMENT_CLIENT_SECRET
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: user-management-secrets
                key: USER_MANAGEMENT_SESSION_SECRET
          - name: NODE_ENV
            value: "production"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: user-management-secrets
                key: USER_MANAGEMENT_JWT_SECRET
